question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Nova Scotia is on the east coast of Canada.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Hungary is the only country in the world beginning with H.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "There are no deserts in Europe.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Greenland is almost as big as Africa.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Ottawa is the capital of Canada.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "The Republic of Malta is the smallest microstate worldwide.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Toronto is the capital city of the North American country of Canada.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "A group of islands is called an &#039;archipelago&#039;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Rhode Island is actually located on the US mainland, despite its name.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "There is a city called Rome in every continent on Earth.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
